checkpoint_monitor_corrector:
  _target_: utils.CorrectorMetricEnabledModelCheckpoint
  start_monitor_step: 0
  monitor: val/corrector_nll
  mode: min
  save_top_k: 1
  save_last: False
  dirpath: ${checkpointing.save_dir}/checkpoints
  filename: best_corrector
  auto_insert_metric_name: False
  verbose: True
