checkpoint_monitor:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/nll
  mode: min
  save_top_k: 1
  save_last: False
  dirpath: ${checkpointing.save_dir}/checkpoints
  filename: best
  auto_insert_metric_name: False
  verbose: True
